
trigger:
- none

pool:
  vmImage: 'windows-latest'

pr:
- master

steps:
- checkout: self
  persistCredentials: true
  clean: true
- task: CmdLine@2
  inputs:
    script: |
      git config --global user.email "glushin.evgeniy@gmail.com"
      git config --global user.name "evgeniy-glushin"

      ECHO SOURCE BRANCH IS %BUILD_SOURCEBRANCH%

      ECHO System.PullRequest.SourceBranch IS %SYSTEM_PULLREQUEST_SOURCEBRANCH%

      SET originSourceBranch=origin/%BUILD_SOURCEBRANCH:refs/heads/=%
      SET sourceBranch=%originSourceBranch:~7% 

      ECHO SOURCE BRANCH IS with removed origin %sourceBranch%

      git checkout master
      git pull origin master

      echo git checkout %sourceBranch%
      git checkout %sourceBranch%
      git pull origin %sourceBranch%

      echo git diff --name-only HEAD@{0} HEAD@{1}
      git diff --name-only HEAD@{0} HEAD@{1}
      echo done

      echo git diff --name-only master..%sourceBranch%
      git diff --name-only master..%sourceBranch%
      echo done

      echo git diff --name-only master..%sourceBranch%
      git diff --name-only master..%sourceBranch% > diff.txt
      echo done

      echo git add ./
      git add ./

      echo git commit -m "Compare changes with the target branch"
      git commit -m "Compare changes with the target branch"

      echo git push origin
      git push origin