# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Trying to exec git command

      git checkout develop
      git fetch

      git checkout master
      git fetch

      echo git diff --name-only HEAD@{0} HEAD@{1}
      git diff --name-only HEAD@{0} HEAD@{1}
      echo done

      echo git diff --name-only master..develop
      git diff --name-only master..develop
      echo done

      echo git rev-parse --verify HEAD
      git rev-parse --verify HEAD
      echo done
