# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Trying to exec git command
      
      git checkout master
      git fetch
      git pull

      echo starting diff...

      git diff --name-only HEAD@{0} HEAD@{5}
      # git log -3

      echo Diff is done
