# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Trying to exec git command

      ECHO SOURCE BRANCH IS %BUILD_SOURCEBRANCH%

      SET sourceBranch=origin/%BUILD_SOURCEBRANCH:refs/heads/=%

      git checkout master
      git pull origin master

      git checkout %sourceBranch%
      git pull origin %sourceBranch%

      echo git diff --name-only HEAD@{0} HEAD@{1}
      git diff --name-only HEAD@{0} HEAD@{1}
      echo done

      echo git diff --name-only master..sourceBranch
      git diff --name-only master..%sourceBranch% > diff.txt
      echo done

      echo git commit -m "Compare changes with the target branch"
      git commit -m "Compare changes with the target branch"
      git push origin