
trigger:
- develop

pool:
  vmImage: 'windows-latest'

pr:
- none

steps:
- checkout: self
  persistCredentials: true
  clean: true
- task: CmdLine@2
  inputs:
    script: |
      git config --global user.email "glushin.evgeniy@gmail.com"
      git config --global user.name "evgeniy-glushin"

      SET sourceBranch=%SYSTEM_PULLREQUEST_SOURCEBRANCH% 

      ECHO SOURCE BRANCH IS %sourceBranch%

      git checkout develop
      git pull origin develop

      echo git checkout %sourceBranch%
      git checkout %sourceBranch%
      git pull origin %sourceBranch%

      echo git diff --name-only develop..%sourceBranch%
      git diff --name-only develop..%sourceBranch%
      git diff --name-only develop..%sourceBranch% > diff.txt
      echo done

      echo git add ./
      git add ./

      echo git commit -m "Compare changes with the target branch"
      git commit -m "Compare changes with the target branch [skip ci]"

      echo git push origin
      git push origin
